//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public long BookingPID { get; set; }
        public Nullable<int> BookedFreight { get; set; }
        public Nullable<int> LabourExpense { get; set; }
        public Nullable<int> VehicleFreight { get; set; }
        public Nullable<int> BillingCharges { get; set; }
        public Nullable<int> OtherExpense { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public System.DateTime DOM { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> QuotationFID { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual Quotation Quotation { get; set; }
    }
}
