//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.Contact_RoadLine_Mapping = new HashSet<Contact_RoadLine_Mapping>();
        }
    
        public int ContactPID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Rating { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> UserTypeFID { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact_RoadLine_Mapping> Contact_RoadLine_Mapping { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
