//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_RoadLine_Mapping
    {
        public int ContactRoadLineMappingPID { get; set; }
        public Nullable<int> ContactFID { get; set; }
        public Nullable<int> RoadLineFID { get; set; }
    
        public virtual RoadLine RoadLine { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
