//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int ErrorPID { get; set; }
        public string Message { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string TargetSite { get; set; }
        public string StackTrace { get; set; }
        public Nullable<long> UserFID { get; set; }
    
        public virtual User User { get; set; }
    }
}
