//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Good()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public long GoodsPID { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<int> MinWeight { get; set; }
        public Nullable<int> MaxWeight { get; set; }
        public Nullable<int> Freight { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string VehicleLength { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> VehicleTypeFID { get; set; }
        public Nullable<int> MaterialTypeFID { get; set; }
        public Nullable<long> UserFID { get; set; }
        public Nullable<long> MobileNumber { get; set; }
        public string LoadingCharges { get; set; }
        public string UnloadingCharges { get; set; }
        public string PackagingCharges { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual MaterialType MaterialType { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual User User { get; set; }
    }
}
