//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTP
    {
        public long OTPPID { get; set; }
        public int OTPNumber { get; set; }
        public Nullable<long> MobileNumber { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string CreationStatus { get; set; }
        public string Details { get; set; }
        public Nullable<int> NoOfTry { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
