//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int TokenPID { get; set; }
        public string Value { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<long> UserFID { get; set; }
    
        public virtual User User { get; set; }
    }
}
