//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail
    {
        public long VehicleDetailPID { get; set; }
        public Nullable<short> Length { get; set; }
        public string WeightCapacity { get; set; }
        public string Description { get; set; }
        public Nullable<int> VehicleTypeFID { get; set; }
    
        public virtual VehicleType VehicleType { get; set; }
    }
}
